# Copyright (C) 2026 Aleksa Dimitrijević. AGPL-3.0-or-later.
# Development tools only; not a production plugin deployment image.
ARG PHP_VERSION=8.5
FROM docker.io/library/composer:2 AS composer
FROM docker.io/library/php:${PHP_VERSION}-cli-bookworm
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates gettext git unzip \
        libfreetype6-dev libicu-dev \
        libjpeg62-turbo-dev libpng-dev libzip-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j2 gd intl mysqli zip \
    && apt-get clean
COPY --from=composer /usr/bin/composer /usr/local/bin/composer
WORKDIR /workspace
